default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: db
  username: cangerana
  password: hypersecrety

development:
  <<: *default
  database: zenrunner

test:
  <<: *default
  database: zenrunner_api_test

production:
  <<: *default
  database: zenrunner_api_production
  host: localhost
  username: postgres
  password: postgres
